name: Terraform

on:
push:
branches:
- main
pull_request:

permissions:
contents: read
id-token: write

jobs:
terraform:
name: Terraform
runs-on: ubuntu-latest

```
defaults:
  run:
    shell: bash
    working-directory: vm_template

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Authenticate to Google Cloud
    id: auth
    uses: google-github-actions/auth@v2
    with:
      workload_identity_provider: projects/826364797512/locations/global/workloadIdentityPools/github-wlif/providers/github
      service_account: github-wlif@project-9daeb647-2a9c-4b5f-a21.iam.gserviceaccount.com

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3

  - name: Terraform Init
    run: terraform init

  - name: Terraform Validate
    run: terraform validate

  - name: Terraform Plan
    run: terraform plan -input=false -var-file="vm.tfvars"

  - name: Terraform Apply
    if: github.ref == 'refs/heads/main'
    run: terraform apply -auto-approve -input=false -var-file="vm.tfvars"
```
